[package]
name = "stm32-gpio-monitor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdb-protocol = "0.1.0"
clap = { version = "3.1.10", features = ["derive"] }
anyhow = "*"
hex = "*"
